### ISSUE TITLE
Setting IFS in exec-env breaks asdf-direnv logging

### ISSUE THREAD

**Issue by detvdl** [asdf-community/asdf-kotlin#22]
Hi,

I am using ASDF with both the [asdf-direnv](https://github.com/asdf-community/asdf-direnv) plugin and this asdf-kotlin plugin.
I recently encountered an issue where the default logging of [direnv](https://github.com/direnv/direnv) was being broken up by many newlines after sourcing the asdf-kotlin environment.

After a short investigation, I figured out that the following line was the culprit for this behaviour:
https://github.com/asdf-community/asdf-kotlin/blob/ce20398cb731f755ffff16e6188ae49b2807abb5/bin/exec-env#L3

This ends up being problematic, because the `exec-env` script is being sourced by direnv in a loop, when using the asdf-direnv integration.
You can see that when looking at an environment definition example:
```txt
log_status using asdf kotlin 1.6.10
PATH_add /Users/<user>/.asdf/installs/kotlin/1.6.10/kotlin-native/bin
PATH_add /Users/<user>/.asdf/installs/kotlin/1.6.10/kotlinc/bin
ASDF_INSTALL_TYPE='version' ASDF_INSTALL_VERSION='1.6.10' \
    ASDF_INSTALL_PATH='/Users/<user>/.asdf/installs/kotlin/1.6.10' \
    source_env /Users/<user>/.asdf/plugins/kotlin/bin/exec-env
...
```

This script is being sourced by the [source_env](https://github.com/direnv/direnv/blob/a446746a6da32e9c3a9fe14905502a0d368c7c07/stdlib.sh#L322-L357) function, after which it breaks all invocations of the [log_status](https://github.com/direnv/direnv/blob/a446746a6da32e9c3a9fe14905502a0d368c7c07/stdlib.sh#L135) and [log_error](https://github.com/direnv/direnv/blob/a446746a6da32e9c3a9fe14905502a0d368c7c07/stdlib.sh#L154) functions.

That is because they both use `msg=$*` to concatenate their arguments into a single string for printing, and removing the space-character from `IFS` breaks that expected functionality.

I understand migrating all scripts to [Strict Bash](http://redsymbol.net/articles/unofficial-bash-strict-mode/) conventions, but I would propose one of the following steps:

1. Remove this line, as it is not effectively being **used** in this script
2. Reset `IFS` back to its original value after the script has executed
3. Wrap everything in a function and manage the modifications to `IFS` as a local variable

An example of how 3 would look:
```bash
#!/usr/bin/env bash
set -eo pipefail

export_kotlin_home() {
    local IFS=$'\n\t'
    if [[ -z ${KOTLIN_HOME:-""} ]]; then
      export KOTLIN_HOME=${ASDF_INSTALL_PATH}/kotlinc
    fi
}

export_kotlin_home
```

**Comment by missingcharacter** [comment]
Yeah, I'm ok with this compromise, would you be ok testing the change from this branch? https://github.com/asdf-community/asdf-kotlin/pull/23
