### ISSUE TITLE
Kotlin native portion of download failing

### ISSUE THREAD

**Issue by samdcoding** [asdf-community/asdf-kotlin#60]
## Describe the bug

For versions 1.9.21 and up, the plugin is producing an error on download.

## Steps to reproduce

When running asdf install with the following `.tool-versions` file:

```
kotlin 1.9.24
```

The following error occurs
![image](https://github.com/asdf-community/asdf-kotlin/assets/157138305/0eed7d5e-d9be-465e-a528-160cd11da007)

Same behaviour occurs when running: `asdf install kotlin 1.9.24`

**Comment by samdcoding** [comment]
I uninstalled and reinstalled and it seemed to resolve itself - weird issue

**Comment by MathisGuillet1** [comment]
Same here, I fixed by running `asdf plugin update kotlin`
